// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0

package database

import (
	"database/sql"
	"time"
)

type Article struct {
	ID          int64
	Title       string
	Description string
	Body        string
	CreatedAt   time.Time
	UpdatedAt   time.Time
	ScheduledAt sql.NullTime
	PublishedAt sql.NullTime
	DeletedAt   sql.NullTime
}

type ArticleRead struct {
	ID        int64
	ArticleID int64
	ReadAt    time.Time
}

type ArticleTag struct {
	ID        int64
	ArticleID int64
	TagName   string
}

type Tag struct {
	Name string
}
