// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.30.0
// source: queries.sql

package database

import (
	"context"
	"database/sql"
	"time"
)

const createArticle = `-- name: CreateArticle :one
INSERT INTO
    articles (title, description, body, scheduled_at)
VALUES
    (?, ?, ?, ?) RETURNING id,
    created_at
`

type CreateArticleParams struct {
	Title       string
	Description string
	Body        string
	ScheduledAt sql.NullTime
}

type CreateArticleRow struct {
	ID        int64
	CreatedAt time.Time
}

// Article CRUD Operations
func (q *Queries) CreateArticle(ctx context.Context, arg CreateArticleParams) (CreateArticleRow, error) {
	row := q.db.QueryRowContext(ctx, createArticle,
		arg.Title,
		arg.Description,
		arg.Body,
		arg.ScheduledAt,
	)
	var i CreateArticleRow
	err := row.Scan(&i.ID, &i.CreatedAt)
	return i, err
}
